FROM node:14-alpine

ENV APP_HOME="/home/app/mcitmocks"

RUN mkdir -p ${APP_HOME} && chown -R node:node ${APP_HOME}

WORKDIR ${APP_HOME}

COPY package*.json ./
RUN yarn

COPY . . 

EXPOSE 8000

ADD entrypoint.prod.sh /entrypoint.prod.sh 
RUN chmod +x /entrypoint.prod.sh 

CMD /entrypoint.prod.sh 