version: "3"

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5432
    environment:
      POSTGRES_DB: mcitmocks_dev
      POSTGRES_USER: mcitmocks
      POSTGRES_PASSWORD: password

  server:
    build:
      context: .
      dockerfile: Dockerfile.ci
    container_name: server
    ports:
      - 8000:8000
    depends_on:
      - database
    environment:
      DATABASE_URL: postgresql://mcitmocks:password@database:5432/mcitmocks_dev
      WAIT_HOSTS: database:5432
