version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/node:16.4.1
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: cp .env.example .env
      - run: yarn docker:ci
      - run: docker-compose down

workflows:
  build_and_test:
    jobs:
      - build_and_test
