version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/node:16.4.1
    steps:
      - checkout
      - run: yarn docker:ci
      - run: yarn test

workflows:
  build_and_test:
    - build_and_test
